[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name        = "vdk"
languages   = ["CXX", "ASM_MASM"]
description = "vdk - vulnerable driver kit"

[options]
VDK_BUILD_EXAMPLE = false

[conditions]
build-example = "VDK_BUILD_EXAMPLE"

[target.ntdll]
type = "interface"
include-directories = ["lib/ntdll"]
link-directories    = ["lib/ntdll"]
x32.link-libraries  = ["ntdll_x86"]
x64.link-libraries  = ["ntdll_x64"]

[target.vdk]
type                = "static"
condition           = "windows"
sources             = ["lib/vdk/**.cpp", "lib/vdk/**.hpp", "lib/vdk/**.asm"]
compile-features    = ["cxx_std_20"]
compile-options     = ["/MT", "/GS-"]
link-libraries      = ["ntdll"]
link-options        = ["/INCREMENTAL:NO"]
include-directories = ["lib/ntdll", "lib/"]

[target.example]
condition           = "build-example"
type                = "executable"
sources             = ["example/**.cpp", "example/**.hpp"]
compile-features    = ["cxx_std_20"]
link-options        = ["/INCREMENTAL:NO"]
link-libraries      = ["vdk"]
include-before      = ["cmake/msvc-static-runtime.cmake"]